quartz:
  enabled: true

server:
  port: 8866

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz_demo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver



